const types = {
  GET_SALAO: '@salao/GET',
  UPDATE_SALAO: '@salao/UPDATE',
  ALL_SERVICOS: '@salao/ALL_SERVICOS',
  UPDATE_SERVICOS: '@salao/UPDATE_SERVICOS',
  UPDATE_AGENDAMENTO: '@salao/UPDATE_AGENDAMENTO',
  UPDATE_FORM: '@salao/UPDATE_FORM',
  FILTER_AGENDA: '@salao/FILTER_AGENDA',
  UPDATE_AGENDA: '@salao/UPDATE_AGENDA',
  UPDATE_COLABORADORES: '@salao/UPDATE_COLABORADORES',
  RESET_AGENDAMENTO: '@salao/RESET_AGENDAMENTO',
  SAVE_AGENDAMENTO: '@salao/SAVE_AGENDAMENTO',
};

export default types;
